# Generated by Django 5.2.17 on 2026-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(help_text='Target Adapt.io account email', max_length=254)),
                ('filters', models.JSONField(default=dict, help_text='Search filters applied on Adapt.io')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_path', models.CharField(blank=True, help_text='Local file path or Supabase Storage key', max_length=500)),
                ('result_url', models.URLField(blank=True, help_text='Supabase storage direct / signed download URL', max_length=1000)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraping Task',
                'verbose_name_plural': 'Scraping Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
