# Generated by Django 5.2.17 on 2026-08-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_candidates_generated',
            field=models.PositiveIntegerField(default=0, help_text='Total email permutation candidate pairs generated'),
        ),
        migrations.AddField(
            model_name='task',
            name='total_scraped_leads',
            field=models.PositiveIntegerField(default=0, help_text='Total raw prospect leads scraped from Adapt.io'),
        ),
        migrations.AddField(
            model_name='task',
            name='total_verified_emails',
            field=models.PositiveIntegerField(default=0, help_text='Total deliverable verified emails confirmed by MailTester'),
        ),
        migrations.AddField(
            model_name='task',
            name='verified_leads',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of verified lead contacts with valid emails'),
        ),
    ]
