# Generated by Django 6.1 on 2026-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_total_candidates_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='logs',
            field=models.JSONField(blank=True, default=list, help_text='Chronological event logs with timestamps'),
        ),
    ]
