# Generated by Django 6.1 on 2026-09-16 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_name_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVProcessTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, default='', help_text='Custom name or label for the CSV processing task', max_length=255)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original uploaded CSV filename', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total rows in the uploaded CSV')),
                ('valid_emails_count', models.PositiveIntegerField(default=0, help_text='Count of leads that had an existing valid business email')),
                ('personal_emails_removed_count', models.PositiveIntegerField(default=0, help_text='Count of personal/free emails removed')),
                ('missing_emails_count', models.PositiveIntegerField(default=0, help_text='Count of leads without a valid business email')),
                ('combinations_generated_count', models.PositiveIntegerField(default=0, help_text='Count of candidate combination rows generated')),
                ('result_path', models.CharField(blank=True, help_text='Local path or Supabase Storage key for the primary result CSV', max_length=500)),
                ('result_url', models.URLField(blank=True, help_text='Download URL for primary result CSV', max_length=1000)),
                ('combinations_path', models.CharField(blank=True, help_text='Local path or Supabase Storage key for combinations CSV', max_length=500)),
                ('combinations_url', models.URLField(blank=True, help_text='Download URL for combinations CSV', max_length=1000)),
                ('valid_leads_path', models.CharField(blank=True, help_text='Local path or Supabase Storage key for clean business leads CSV', max_length=500)),
                ('valid_leads_url', models.URLField(blank=True, help_text='Download URL for clean business leads CSV', max_length=1000)),
                ('preview_data', models.JSONField(blank=True, default=list, help_text='First few processed preview rows for UI rendering')),
                ('error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('logs', models.JSONField(blank=True, default=list, help_text='Chronological event logs')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the CSV file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csv_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Process Task',
                'verbose_name_plural': 'CSV Process Tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
