# Generated by Django 6.1 on 2026-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_csvprocesstask'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvprocesstask',
            name='duplicates_removed_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of duplicate emails removed'),
        ),
    ]
