# Generated by Django 6.1 on 2026-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_csvprocesstask_duplicates_removed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvprocesstask',
            name='current_step',
            field=models.CharField(blank=True, default='', help_text='Current processing step', max_length=100),
        ),
        migrations.AddField(
            model_name='csvprocesstask',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Current status message'),
        ),
        migrations.AddField(
            model_name='csvprocesstask',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Progress percentage (0 - 100)'),
        ),
        migrations.AddField(
            model_name='csvprocesstask',
            name='total_verified_emails',
            field=models.PositiveIntegerField(default=0, help_text='Count of verified deliverable emails after MailTester check'),
        ),
        migrations.AddField(
            model_name='csvprocesstask',
            name='uploaded_file_path',
            field=models.CharField(blank=True, default='', help_text='Local path to uploaded CSV file', max_length=500),
        ),
        migrations.AddField(
            model_name='csvprocesstask',
            name='verified_leads',
            field=models.JSONField(blank=True, default=list, help_text='Final list of verified prospect lead records'),
        ),
        migrations.AlterField(
            model_name='csvprocesstask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
